name: Build and Package Java Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '1.8'

    - name: Build with Maven
      run: mvn clean package

    - name: Prepare artifacts directory
      run: mkdir -p artifacts

    - name: Copy JAR to artifacts
      run: cp target/*.jar artifacts/

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v2
      with:
        name: javabridgeproject
        path: artifacts/*.jar
